### ISSUE TITLE
Where's the source???

### ISSUE THREAD

**Issue by aaronliu0130** [j0lol/stellar#1]
You say you want to remain open source but you don't do that???

Apologies if modpacks don't actually have sources, but still a modlist would be nice

**Comment by j0lol** [comment]
i think i forgot lol

**Comment by j0lol** [comment]
i probably made this with like a packwiz config file

**Comment by j0lol** [comment]
why tf did i even make this repo lmao. its probably in my files somewhere. if i find the source ill push it here

**Comment by j0lol** [comment]
found it! sorry about forgetting to put the source for like a year LMAO. not that anyone cares about a modpack for a dead version anyway but whatever

**Comment by j0lol** [comment]
also modrinth should really add mod listings to modpacks
